apiVersion: v1
kind: Service
metadata:
  name: trading
  labels:
    app: trading
spec:
  selector:
    app: trading
    tier: app-server
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading
  labels:
    app: trading
spec:
  selector:
    matchLabels:
      app: trading
      tier: app-server
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: trading
        tier: app-server
    spec:
      containers:
      - image: mm444/express-trading-app-arm #image to run on ARM based system
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        name: trading
        env:
        - name: DB_NAME
          value: trader_db
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3001
          name: trading